/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bonk;

import Bonk.Framework.Item;

import java.util.Random;

public class App {

    public static void main(String[] args) {


    }



}
